server:
  port: 30000

spring:
  application:
    name: fakeSite

logging:
  level:
    org.springframework.web: DEBUG
    # demo.test.controller: DEBUG
    demo.test.mapper: DEBUG
    demo.tool.mapper: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "[%p] [%d{yyyy-MM-dd HH:mm:ss}][%c]%m%n [%thread] %-5level %logger{36}"
      
  file: /home/u2/logs/flog.log